export default [
  { Action: 'MultiOfflineBusinessDocument', params: [{ DocumentIDs: [ '126', '127', '128', '129'], BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'MultiPublishBusinessDocument', params: [{ DocumentIDs: [  '126', '127', '128', '129'], BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'ListBusinessDocumentVersion', params: [{ DocumentID: 137, Limit: 10, Offset: 0, BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'EmployeeSaveBusinessDocumentVersionToDraft', params: [{ DocumentID: 137, VersionID: 1219241, BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'PublishBusinessDocumentVersion', params: [{ DocumentID: 137, VersionID: 1219241, BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'GetBusinessDocumentStructure', params: [{ BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'GetLatestBusinessDocument', params: [{ DocumentID: 68 , BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'PublishBusinessDocument', params: [{ DocumentID: 68, BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'OfflineBusinessDocument', params: [{ DocumentID: 68, BusinessID: '5' },{ name: 'wuchenkai' }] },
  // { Action: 'AddBusinessDocument', params: [{ BusinessID: '5', Title: '测试用例' + Math.random(), MainPage: 0, KeyWords: '' },{ name: 'wuchenkai' }] },
  // { Action: 'DelBusinessDocument', params: [{ Title: '随机' + random, BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'EmployeeAddAndDelBusinessDocument', params: [{ BusinessID: '5', Title: '测试用例' + Math.random(), MainPage: 0, KeyWords: '' },{ name: 'wuchenkai' }] },
  { Action: 'UpdateBusinessDocument', params: [{ DocumentID: 68, Title: '产品简介', MainPage: 0, KeyWords: '', BusinessID: 5 },{ name: 'wuchenkai' }] },
  { Action: 'SaveBusinessDocument', params: [{ DocumentID: 68, Content: '## 搞事情', BusinessID: '5' },{ name: 'wuchenkai' }] },
  { Action: 'UpdateBusinessDocumentIndex', params: [{ BusinessID: '5',List: [{ DocumentID: 127, Index: 1, ParentID: 126 },{ DocumentID: 128, Index: 2, ParentID: 126 },{ DocumentID: 129, Index: 3, ParentID: 126 }] },{ name: 'wuchenkai' }] },
  // { Action: 'UpdateBusiness', params: [{}] },
  // { Action: 'CreateBusiness', params: [{}] },
  { Action: 'ListServices', params: [{}] },
  { Action: 'UpdateService', params: [{}] },
  { Action: 'ListApis', params: [{}] },
  { Action: 'CreateApi', params: [{}] },
  { Action: 'UpdateApi', params: [{}] },
  { Action: 'PublishApi', params: [{}] },
  { Action: 'ListServiceAccessKey', params: [{}] },
  { Action: 'CreateServiceAccessKey', params: [{}] },
  { Action: 'UpdateServiceAccessKey', params: [{}] },
  { Action: 'DelServiceAccessKey', params: [{}] },
];